// "x": Wall, "@": Player, "o": Coin, "G": Snitch
// "!" Lava "v": DripLavaSlow, "V": DripLavaFast, "a": RisingLavaSlow, "A": RisingLavaFast 
// "e": SlowEnemy, "E": FastEnemy, "b": BouncerEnemySlow, "B": BouncerEnemyFast

// Jump = 4 x, Enemies and Coins must be a block aboce the floor
var GAME_LEVELS = [
  ["                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                   o                                                        ",
   "                                                       o                                    ",
   " x G                             xxxxx                                                      ",
   " x                                         o  o       xxxx                                 x",
   " x                                                                o                        x",
   " xxxxxxx      xx                          xxxxxx                                         o x",
   "              x                                                 xxx            o           x",
   "              x                                 E             xxxxx                  xxxxxxx",
   "              x             @                               xxxxxxx       x     e   xx      ",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx a xxxxxxxxx       x         xx      ",
   "                                                  x!!!!!!!x       x   a   xxxxxxxxxxxx      ",
   "                                                  x!!!!!!!x       x!!!!!!!x                 ",
   "                                                  x!!!!!!!x       x!!!!!!!x                 ",
   "                                                  xxxxxxxxx       x!!!!!!!x                 ",
   "                                                                  x!!!!!!!x                 ",
   "                                                                  xxxxxxxxx                 "],
  ["                                                                                                                 x",
   "                                                                                                                 x",
   "                                                                                                                 x",  
   "                                                                                                                 x",  
   "                                                                                                                 x",
   "                                                                                                                 x",
   "                                         B                                                         o             x",
   "                                                                                    o      o                     x",
   "                                                                                                  xxx         xxxx",
   "                                                                 o                  xx     o      xxx       E xxxx",
   "                                         o                                   xxxx                 xxx         xxxx",
   "                                                                 o                        xxx                    x",
   "          @      o o              xxxxxxxxxxxxxxxx                                                       o       x",
   "                               xxxxxxxxxxxxxxxxxxxxxx          xxxxx      xxxxxx                                 x",
   "      xxxxxxxxxxxxxxx      xxxxxxxxxx       xxxxxxxxxxxxx a  a       A  A xxxxxx                      xxxxxxx    x",
   "     xxxxxxxxxx            xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "    xxxxxxxx               xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx      G      xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx             xxxxxxxxxxxxVxxxxxxxxxxvxxxxxxxxx                                 x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx    xxxxx                                                                      x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx                                                                               x",
   "!!!!xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx                                                                               x",
   "!!!!XXXXXXXX!!!!!!!!!!!!!!!xxxxxxx           xxx                                 xx                              x",
   "!!!!XXXXXXXX!!!!!!!!!!!!!!!xxxxxxx           xxx    E                            xx                              x",
   "!!!!XXXXXXXX!!!!!!!!!!!!!!!xxxxxxx           xxx                                 xx                              x",
   "!!!!XXXXXXXX!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    x"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                           o           o                      ",
   "      @                                                                                      xxx   xxx        ",
   "                                                                   x       E           E     x!! o !!x        ",
   "     xxx          o  o                 o            o              x                         x!!   !!x        ",
   "    xxxxx                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!   !!x        ",
   "    xxxxx       xxxxxxxx      xx       e            e    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!! o !!x        ",
   "    xxxxx       xxxxxxxx      xx                         xxxxxxxxxxxxxxxxx                   x!!   !!x        ",
   "   xxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                           x!x   x!x        ",
   "   xxxxxxx                    xx                                               B             xvx o x!x        ",
   "   xxxxxxx                    xx          b            b                                           x!x        ",
   "  xxxxxxxxx                   xx                                                                   x!x        ",
   "  xxxxxxxxx                   xx                                                                   x!x        ",
   "  xxxxxxxxx                   xx          o            o                       o                   x!x        ",
   "  xxxxxxxxx                   xx                                                                   x!x        ",
   "  xxxxxxxxx                   xx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x        ",
   "   xxxxxxx                    xx    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        ",
   "   xxxxxxx                    xx   xxxxxxvxxxxxxxVxxxxxxxvxVxxxxxxxVxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x        ",
   "   xxxxxxx                    xx                                                                    !         ",
   "    xxxxx                     xxx                                                        o          !         ",
   "    xxxxx                     xx                                                                    !         ",
   "    xxxxx                     xx                                                        xxx         !         ",
   "    xxxxx                     xx                                                       xx!xx        !         ",
   "    xxxxx                     xx                                                      xx!!!xx       !         ",
   "     xxx          G           xx             o        o       o         o            xx!!!!!xx      !         ",
   "     xxx                      xx                                                     x!!!!!!!x      !         ",
   "     xxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!         ",
   "      x                                                                                             !         ",
   "      x     aA xxxxxxx   Aa                                                                         !         ",],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
